name: financial_document
document_type: FINANCIAL_DOCUMENT
schema_version: "1.0"
description: "Base financial document schema configuration"
created_at: "2025-03-15T20:45:00Z"
updated_at: "2025-03-15T20:45:00Z"

fields:
  - name: document_id
    path: "metadata.document_id"
    type: string
    required: true
    description: "Unique document identifier"
    validation: "len(value) > 0"

  - name: document_date
    path: "metadata.document_date"
    type: date
    required: true
    description: "Document date"
    validation: "is_date()"

  - name: amount
    path: "metadata.amount"
    type: decimal
    required: true
    description: "Document amount"
    validation: "is_decimal() and value >= 0"

  - name: currency
    path: "metadata.currency"
    type: string
    required: false
    description: "Currency code (e.g., USD)"
    default: "USD"
    validation: "len(value) == 3"

  - name: issuer_name
    path: "metadata.issuer_name"
    type: string
    required: true
    description: "Issuer name"
    validation: "len(value) > 0"

  - name: issuer_address
    path: "metadata.issuer_address"
    type: string
    required: false
    description: "Issuer address"

  - name: recipient_name
    path: "metadata.recipient_name"
    type: string
    required: false
    description: "Recipient name"

  - name: recipient_address
    path: "metadata.recipient_address"
    type: string
    required: false
    description: "Recipient address"

validations:
  - name: validate_amount
    description: "Validate that amount is positive"
    condition: "amount > 0"
    message: "Amount must be positive"
    level: "error"

  - name: validate_currency
    description: "Validate that currency is a valid code"
    condition: "currency in ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY']"
    message: "Currency must be a valid code"
    level: "warning"

metadata:
  schema_type: "base"
  target_format: "json"
