name: invoice
document_type: invoice
schema_version: "1.0.0"
description: "Invoice document schema version 1.0.0"

fields:
  - name: invoice_number
    path: invoice_number
    type: string
    required: true
    description: "Unique invoice identifier"
    validation: "len(value) > 0"

  - name: payment_type
    path: payment_type
    type: string
    required: true
    description: "Type of payment (legacy field)"
    validation: "value in ['credit', 'debit', 'cash']"

  - name: transaction_id
    path: transaction_id
    type: string
    required: true
    description: "Transaction identifier"
    validation: "len(value) > 0"

  - name: amount
    path: amount
    type: string
    required: true
    description: "Invoice amount"
    validation: "float(value) > 0"

  - name: currency
    path: currency
    type: string
    required: true
    description: "Currency code"
    validation: "len(value) > 0"

validations:
  - name: valid_amount
    description: "Ensure amount is a valid number"
    condition: "isinstance(float(amount), float)"
    message: "Amount must be a valid number"
    level: "error"
