@startuml
skinparam classAttributeIconSize 0

package "1a31ce608336_add_cascade_delete_relationships" {
  class Functions <<(F,orange)>> {
    + upgrade() -> Any
    + downgrade() -> Any
  }
}

' Relationships
@enduml