@startuml
skinparam classAttributeIconSize 0

package "backend_pre_start" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC init(db_engine: Engine) -> None
    Visibility.PUBLIC main() -> None
  }
}

' Relationships
@enduml