@startuml
skinparam classAttributeIconSize 0

package "conftest" {
  class Functions <<(F,orange)>> {
    +db() -> Generator[Session, None, None]
    +client() -> Generator[TestClient, None, None]
    +superuser_token_headers(client: TestClient) -> dict[str, str]
    +normal_user_token_headers(client: TestClient, db: Session) -> dict[str, str]
  }
}

' Relationships
@enduml