@startuml
skinparam classAttributeIconSize 0

package "config" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC parse_cors(v: Any) -> list[str] | str
  }
  class Settings {
    Visibility.PUBLIC model_config: Any
    Visibility.PUBLIC API_V1_STR: str
    Visibility.PUBLIC SECRET_KEY: str
    Visibility.PUBLIC ACCESS_TOKEN_EXPIRE_MINUTES: int
    Visibility.PUBLIC FRONTEND_HOST: str
    Visibility.PUBLIC ENVIRONMENT: Literal['local', 'staging', 'production']
    Visibility.PUBLIC BACKEND_CORS_ORIGINS: Annotated[list[AnyUrl] | str, BeforeValidator(parse_cors)]
    Visibility.PUBLIC PROJECT_NAME: str
    Visibility.PUBLIC SENTRY_DSN: HttpUrl | None
    Visibility.PUBLIC POSTGRES_SERVER: str
    Visibility.PUBLIC POSTGRES_PORT: int
    Visibility.PUBLIC POSTGRES_USER: str
    Visibility.PUBLIC POSTGRES_PASSWORD: str
    Visibility.PUBLIC POSTGRES_DB: str
    Visibility.PUBLIC SMTP_TLS: bool
    Visibility.PUBLIC SMTP_SSL: bool
    Visibility.PUBLIC SMTP_PORT: int
    Visibility.PUBLIC SMTP_HOST: str | None
    Visibility.PUBLIC SMTP_USER: str | None
    Visibility.PUBLIC SMTP_PASSWORD: str | None
    Visibility.PUBLIC EMAILS_FROM_EMAIL: EmailStr | None
    Visibility.PUBLIC EMAILS_FROM_NAME: EmailStr | None
    Visibility.PUBLIC EMAIL_RESET_TOKEN_EXPIRE_HOURS: int
    Visibility.PUBLIC EMAIL_TEST_USER: EmailStr
    Visibility.PUBLIC FIRST_SUPERUSER: EmailStr
    Visibility.PUBLIC FIRST_SUPERUSER_PASSWORD: str
    Visibility.PUBLIC LOG_LEVEL: str
    Visibility.PUBLIC LOG_FORMAT: str
    Visibility.PUBLIC LOG_FILE: str | None
    Visibility.PUBLIC LOG_ROTATION: bool
    Visibility.PUBLIC LOG_ROTATION_SIZE: int
    Visibility.PUBLIC LOG_ROTATION_BACKUPS: int
    Visibility.PUBLICall_cors_origins() -> list[str]
    Visibility.PUBLICSQLALCHEMY_DATABASE_URI() -> str
    Visibility.PROTECTED_set_default_emails_from() -> Self
    Visibility.PUBLICemails_enabled() -> bool
    Visibility.PROTECTED_check_default_secret(var_name: str, value: str | None) -> None
    Visibility.PROTECTED_enforce_non_default_secrets() -> Self
  }
}

' Relationships
BaseSettings <|-- "config".Settings
@enduml