@startuml
skinparam classAttributeIconSize 0

package "deps" {
  class Functions <<(F,orange)>> {
    +get_db() -> Generator[Session, None, None]
    +get_current_user(session: SessionDep, token: TokenDep) -> User
    +get_current_active_superuser(current_user: CurrentUser) -> User
  }
}

' Relationships
@enduml