@startuml
skinparam classAttributeIconSize 0

package "initial_data" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC init() -> None
    Visibility.PUBLIC main() -> None
  }
}

' Relationships
@enduml