@startuml
skinparam classAttributeIconSize 0

package "main" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC custom_generate_unique_id(route: APIRoute) -> str
  }
}

' Relationships
@enduml