@startuml
skinparam classAttributeIconSize 0

package "private" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC create_user(user_in: PrivateUserCreate, session: SessionDep) -> Any
  }
  class PrivateUserCreate {
    Visibility.PUBLIC email: str
    Visibility.PUBLIC password: str
    Visibility.PUBLIC full_name: str
    Visibility.PUBLIC is_verified: bool
  }
}

' Relationships
BaseModel <|-- "private".PrivateUserCreate
@enduml