@startuml
skinparam classAttributeIconSize 0

package "test_private" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC test_create_user(client: TestClient, db: Session) -> None
  }
}

' Relationships
@enduml