@startuml
skinparam classAttributeIconSize 0

package "test_login" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC test_get_access_token(client: TestClient) -> None
    Visibility.PUBLIC test_get_access_token_incorrect_password(client: TestClient) -> None
    Visibility.PUBLIC test_use_access_token(client: TestClient, superuser_token_headers: dict[str, str]) -> None
    Visibility.PUBLIC test_recovery_password(client: TestClient, normal_user_token_headers: dict[str, str]) -> None
    Visibility.PUBLIC test_recovery_password_user_not_exits(client: TestClient, normal_user_token_headers: dict[str, str]) -> None
    Visibility.PUBLIC test_reset_password(client: TestClient, db: Session) -> None
    Visibility.PUBLIC test_reset_password_invalid_token(client: TestClient, superuser_token_headers: dict[str, str]) -> None
  }
}

' Relationships
@enduml