@startuml
skinparam classAttributeIconSize 0

package "users" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC read_users(session: SessionDep, skip: int = 0, limit: int = 100) -> Any
    Visibility.PUBLIC create_user() -> Any
    Visibility.PUBLIC update_user_me() -> Any
    Visibility.PUBLIC update_password_me() -> Any
    Visibility.PUBLIC read_user_me(current_user: CurrentUser) -> Any
    Visibility.PUBLIC delete_user_me(session: SessionDep, current_user: CurrentUser) -> Any
    Visibility.PUBLIC register_user(session: SessionDep, user_in: UserRegister) -> Any
    Visibility.PUBLIC read_user_by_id(user_id: uuid.UUID, session: SessionDep, current_user: CurrentUser) -> Any
    Visibility.PUBLIC update_user() -> Any
    Visibility.PUBLIC delete_user(session: SessionDep, current_user: CurrentUser, user_id: uuid.UUID) -> Message
  }
}

' Relationships
@enduml