@startuml
skinparam classAttributeIconSize 0

package "utils" {
  class Functions <<(F,orange)>> {
    Visibility.PUBLIC random_lower_string() -> str
    Visibility.PUBLIC random_email() -> str
    Visibility.PUBLIC get_superuser_token_headers(client: TestClient) -> dict[str, str]
  }
}

' Relationships
@enduml