# Workspace-specific Ruff configuration
# This file can be copied to project subdirectories to override global settings

# Target Python version
target-version = "py310"

# Line length
line-length = 88

# Exclude patterns
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "alembic",
    ".mypy_cache",
    ".ruff_cache",
]

# Formatter configuration
[formatter]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true

# Linter configuration
[lint]
# Enable specific rule sets (can be customized per project)
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "COM",  # flake8-commas
    "C90",  # mccabe complexity
    "T20",  # flake8-print
    "PT",   # flake8-pytest-style
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "ERA",  # eradicate (commented out code)
    "PL",   # pylint
    "TRY",  # tryceratops
    "RUF",  # ruff-specific rules
]

# Rules to ignore (can be customized per project)
ignore = [
    "E501",  # line too long (handled by formatter)
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
    "B904",  # Allow raising exceptions without from e, for HTTPException
    "PLR0913",  # Too many arguments to function call
    "PLR2004",  # Magic value used in comparison
]

# Autofix behavior
fixable = ["ALL"]
unfixable = []

# Maximum McCabe complexity allowed
[lint.mccabe]
max-complexity = 10

# isort configuration
[lint.isort]
known-first-party = ["app"]
known-third-party = ["fastapi", "pydantic", "sqlmodel"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

# pyupgrade configuration
[lint.pyupgrade]
keep-runtime-typing = true

# Per-file ignores
[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports
"tests/**/*.py" = ["PLR2004", "S101"]  # Magic values and assert statements in tests