# Workspace-specific Ruff configuration
# This file can be copied to project subdirectories to override global settings

target-version = "py310"
line-length = 88

exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "alembic",
    ".mypy_cache",
    ".ruff_cache",
]

# Formatter configuration
[formatter]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true

# Linter configuration
[lint]
select = [
    "E", "W", "F", "I", "B", "C4", "UP", "N", "COM", "C90",
    "T20", "PT", "RET", "SIM", "ARG", "ERA", "PL", "TRY", "RUF",
]

ignore = [
    "E501",
    "B008",
    "W191",
    "B904",
    "PLR0913",
    "PLR2004",
]

fixable = ["ALL"]
unfixable = []

[lint.mccabe]
max-complexity = 10

[lint.isort]
known-first-party = ["app"]
known-third-party = ["fastapi", "pydantic", "sqlmodel"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.pyupgrade]
keep-runtime-typing = true

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*.py" = ["PLR2004", "S101"]
