name: pipeline_schema_registry
version: "1.0.0"
description: "Schema registry configuration"

# Schema discovery configuration
discovery:
  paths:
    - utils/pipeline/config/schemas
    - utils/pipeline/config/migrations
  patterns:
    - "*.yaml"
    - "*.yml"
    - "*.json"

# Storage configuration
storage:
  type: file
  path: utils/pipeline/config/schemas

# Validation configuration
validation:
  strict: true
  allow_unknown: false
