@startuml
skinparam classAttributeIconSize 0

package "config" {
  class Functions <<(F,orange)>> {
    +create_config_from_args(args: Any) -> Configuration
    +configure_logging(args: Any) -> logging.Logger
  }
}

' Relationships
@enduml