@startuml
skinparam classAttributeIconSize 0

package "env" {
  class Functions <<(F,orange)>> {
    +get_url() -> Any
    +run_migrations_offline() -> Any
    +run_migrations_online() -> Any
  }
}

' Relationships
@enduml